- hosts: master
  become: true
  gather_facts: true
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: true
  tasks:
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host=10.10.10.50 port=6443 timeout=30"

    - name: join cluster
      shell: "{{ hostvars['k8s-master-1'].join_command }} >> node_joined.log"
      args:
        chdir: /home/codehuri
        creates: node_joined.log
